stages:
  - build
  - release
  - deploy

variables:
  ASSEMBLY_EXTENSION: "dll"

.build_scripts : &build_scripts
  before_script:
    - nuget restore
    - mkdir $env:CI_PROJECT_NAME/lib
    - wget https://gitlab.cern.ch/$env:CI_PROJECT_NAMESPACE/plugin/-/jobs/artifacts/master/raw/plugin/bin/Release/plugin.dll?job=build -OutFile $env:CI_PROJECT_NAME/lib/plugin.dll
  script:
    - msbuild /p:VersionAssembly=$env:CI_COMMIT_TAG /p:Configuration=Release $env:CI_PROJECT_NAME.sln
  after_script:
    - (Get-FileHash $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION -Algorithm SHA1).Hash > $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION.sha1


test_build:
  stage: build
  except:
    - tags
  <<: *build_scripts


build:
  stage: build
  only:
    - tags
  <<: *build_scripts
  artifacts:
    paths:
      - $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION
      - $env:CI_PROJECT_NAME/bin/Release/$env:CI_PROJECT_NAME.$env:ASSEMBLY_EXTENSION.sha1
    expire_in: 1 year


release_version:
  stage: release
  only:
    - tags
  script:
    # Create a release for the current tag
    # This needs to be changed by GitLab
    # Release creation should be 'keyword based'
    - CreateRelease


release_qa:
  stage: deploy
  environment: qa
  only:
    - tags
  script:
    # Update "qa" release name the newest version number
    # This needs to be changed by GitLab
    # Release creation should be 'keyword based'
    - DeployQA


release_production:
  stage: deploy
  environment: production
  when: manual
  only:
    - tags
  script:
    # Update "production" release name the newest version number
    # This needs to be changed by GitLab
    # Release creation should be 'keyword based'
    - DeployProduction
