language: csharp
solution: updates.sln
script:
- wget -P updates/lib/ https://github.com/cern-winagent/plugin/releases/latest/download/plugin.dll
- msbuild /p:Configuration=Release updates.sln
before_deploy:
- sha1sum updates/bin/Release/updates.dll > updates/bin/Release/updates.dll.sha1
deploy:
  provider: releases
  api_key:
    secure: lPn+K4vFcf5QRiYQe8lsFclJZLnHtyy3COqD2bXHpFcwWYaBY/TJPx7D04v9J2d0ud++mxV62ChB8E1uXLGeiEOkiSStpvaTxSdliQtGbrn5f8fDKzsqGQ+wcw9jz1pfvvzvLCRfxCPmyNbwhQRhS7dopV8lY7gK3/88V239vj6qB2d0S9kyiLdkOVFrPA4AXMlcK7JDYsNeMx8vEKgdpXb+CPVqFhX4i0HziUkkfhod1DtVOkDhRHlSQJiQXLR9FRqQCbx8s0jEbacwAOhnQ56BMtjAnN0xfaCTtNI29XoLAynC0855RM1dma0WWz5PRRB1L86nI+bL4B1/2WtPkhSu+kzrbGgjmcUL1Na1iHwQ6Jzu7Jsvu8gWbhEydR9xbUQH1Usrj6Oaz5pFT/VoB87CJdFEcm8pi3yOb/51zI8g8rFP49V134QaaoGxpuuDIbtMILwlyxIGv4371SShGEgO3xnwLIJhBPeBiDtx6H+9Sg0X8mTZO2tkE7gCNArcfk65th6OChgwBJ8qVpC24XQ7ktTl9uPZS1iXrmgh8x1FGaaLagFvStnhyQIt5OJbgH1eZphRX+BplLf2UVAe0cyzMLTSwVFoaAE4sBywl8CRPYdi1abfAAXqdt0HzdWMqlLJgQeSp9OF7L49DjUITR6RYytlCwR6ZnLCDhGTrCM=
  file:
  - updates/bin/Release/updates.dll
  - updates/bin/Release/updates.dll.sha1
  skip_cleanup: true
  overwrite: true
  on:
    repo: cern-winagent/updates
    tags: true
